spring.application.name=dashboard
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db

spring.datasource.username="Database_user"
spring.datasource.password="Database_password"

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensure data.sql runs after Hibernate initializes the schema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true